version: '3.8'

services:
  user-service:
    build:
      context: .
      dockerfile: ./src/user/Dockerfile
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/userdb

  client-service:
    build:
      context: .
      dockerfile: ./src/client/Dockerfile
    ports:
      - "9002:9002"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/clientdb

  task-service:
    build:
      context: .
      dockerfile: ./src/task/Dockerfile
    ports:
      - "9001:9001"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/taskdb

  fields-service:
    build:
      context: .
      dockerfile: ./src/fields/Dockerfile
    ports:
      - "9003:9003"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/fieldsdb

  blogs-service:
    build:
      context: .
      dockerfile: ./src/blogs/Dockerfile
    ports:
      - "9004:9004"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/blogsdb

  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: