version: '3.8'

services:
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001" # Redis Stack browser (web UI)
    environment:
      - REDIS_ARGS=--save "" --appendonly no
    restart: unless-stopped
    networks:
      - microservices-network
  user_image:
    build: ./src/user/
    container_name: user_container
    ports:
      - "9000:9000"
    environment:
      - ENV=development
    networks:
      - microservices-network

  task_image:
    build: ./src/task/
    container_name: task_container
    networks:
      - microservices-network

    ports:
      - "9001:9001"
    environment:
      - ENV=development

  field_image:
    build: ./src/fields/
    container_name: field_container
    networks:
      - microservices-network
    ports:
      - "9003:9003"
    environment:
      - ENV=development

  client_image:
    build: ./src/client/
    container_name: client_container
    ports:
      - "9002:9002"
    networks:
      - microservices-network
    environment:
      - ENV=development
  blog_image:
    build: ./src/blogs/
    container_name: blog_container
    ports:
      - "9004:9004"
   

    environment:
      - ENV=development
    
    networks:
      - microservices-network




networks:
  microservices-network:
    driver: bridge
